// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3nxkdO7V-feLd9SfWIWJLwl8szu2o8u4',
    appId: '1:444423871729:web:755123f42c650550419d50',
    messagingSenderId: '444423871729',
    projectId: 'pocketsights-4936d',
    authDomain: 'pocketsights-4936d.firebaseapp.com',
    storageBucket: 'pocketsights-4936d.appspot.com',
    measurementId: 'G-WY3V1N1GV1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1LuqbOcfVMSb-u9-0JOfyTUl4ZKIC1jg',
    appId: '1:444423871729:android:b3ab0d345183c87d419d50',
    messagingSenderId: '444423871729',
    projectId: 'pocketsights-4936d',
    storageBucket: 'pocketsights-4936d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCp0MokFMXxy0vP4p1VlVsKCBvXcf20Cho',
    appId: '1:444423871729:ios:f23dbe1446a72d7e419d50',
    messagingSenderId: '444423871729',
    projectId: 'pocketsights-4936d',
    storageBucket: 'pocketsights-4936d.appspot.com',
    iosBundleId: 'com.example.artGalleryApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCp0MokFMXxy0vP4p1VlVsKCBvXcf20Cho',
    appId: '1:444423871729:ios:f23dbe1446a72d7e419d50',
    messagingSenderId: '444423871729',
    projectId: 'pocketsights-4936d',
    storageBucket: 'pocketsights-4936d.appspot.com',
    iosBundleId: 'com.example.artGalleryApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3nxkdO7V-feLd9SfWIWJLwl8szu2o8u4',
    appId: '1:444423871729:web:f54c89a60cfe5a41419d50',
    messagingSenderId: '444423871729',
    projectId: 'pocketsights-4936d',
    authDomain: 'pocketsights-4936d.firebaseapp.com',
    storageBucket: 'pocketsights-4936d.appspot.com',
    measurementId: 'G-P21T9RVX92',
  );
}
